config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  get 'orders/info' => 'orders#info'
  get 'supplies/info' => 'supplies#info'

  resources :supplies

  resources :orders

  resources :users
  
  root to: "supplies#index"

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_order, only: [:destroy, :edit, :update]

  def index
    if current_user.admin?
      @orders = Order.order(:user_id).all
    else
      @orders = Order.where("user_id = ?", current_user.id.to_s)
    end

  end

  def create
    @supply = Supply.find(params[:order][:supply_id])

    @total = @supply.price * params[:order][:count].to_f
    if current_user.discount.nil?
      if @total > 2000
        current_user.discount = 20
        User.find_by(:id => current_user.id).update(:discount => 20)
      end
    end

    @order = Order.new({
         :supply_id => params[:order][:supply_id],
         :user_id => current_user.id,
         :count => params[:order][:count].to_f,
         :total => @total * (1 - current_user.discount*0.01),
         :status => params[:order][:status],
         :deliveryDate => params[:order][:deliveryDate]
     })


    respond_to do |format|
      if @order.save
        format.html { render action: :show }
      else
        redirect_to('/supplies')
      end
    end
  end

  def edit
    if !current_user.admin?
      redirect_to('/orders')
    end
  end


  def update

    if params[:order][:status] == 'Ready'
      params[:order][:deliveryDate] = Date.today
    elsif params[:order][:status] == 'Rejected'
      params[:order][:deliveryDate] = ''
    end

    respond_to do |format|
      if @order.update(:status => params[:order][:status], :deliveryDate => params[:order][:deliveryDate] )
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
      else
        redirect_to('/orders')
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def new
    @order = Order.new
    @supply = Supply.find(params[:supply_id])
    @user = User.find(current_user.id)
  end

  def show
    @order = Order.find(params[:id])
  end

  def info

  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel-default panel">
      <div class="panel-heading">
        <h4>Editing order</h4>
      </div>
      <div class="panel-body">

        <p id="notice"><%= notice %></p>

        <p>
          <strong>Order ID:</strong>
          <%= @order.id %>
        </p>

        <p>
          <strong>User ID:</strong>
          <%= @order.user_id %>
        </p>

        <p>
          <strong>Supply ID: </strong>
          <%= @order.supply_id %>
        </p>

        <p>
          <strong>Total:</strong>
          <%= @order.total %> UAH
        </p>

        <p>
          <strong>Delivery Date:</strong>
          <%= @order.deliveryDate %>
        </p>

        <%= form_for(@order) do |f| %>

            <div class="form-group">
              <%= f.label :status, class: 'control-label' %>
              <%= f.select(:status, ['Pending', 'Ready', 'Rejected'], {}, {:class => 'selectpicker'}) %>
            </div>

            <div class="form-group">
              <%= f.submit 'Update', :class => 'btn btn-primary' %>
              <%= link_to 'Back', orders_path, class: 'btn btn-default' %>
            </div>


        <% end %>

      </div>
    </div>
  </div>
</div>

<script>
  $(function(){
      $('.selectpicker').selectpicker();
  });
</script>

app/views/orders/index.html.erb
<% if !@orders.nil? %>

    <div class="container">

      <h1>Orders</h1>

      <p id="notice"><%= notice  %></p>

      <table class="table table-bordered">
        <thead>
        <tr>
          <th class="text-center">User_ID</th>
          <th class="text-center">Supply_ID</th>
          <th class="text-center">Count</th>
          <th class="text-center">Total price</th>
          <th class="text-center">Delivery date</th>
          <th class="text-center">Status</th>
          <th class="text-center">Actions</th>
        </tr>
        </thead>

        <tbody>
        <% @orders.each do |order| %>
            <tr>
              <td><%= order.user_id %></td>
              <td><%= order.supply_id %></td>
              <td><%= order.count %></td>
              <td><%= order.total %></td>
              <td><%= order.deliveryDate %></td>
              <td><%= order.status %></td>
              <td class="text-center">
                <%= link_to 'Show', order, class: 'btn btn-default' %>
                <%= link_to 'Edit', edit_order_path(order), class: 'btn btn-info' %>
                <%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
<% else %>
    <div class="container">
      <h3>
        No orders was made.
      </h3>
    </div>
<% end %>


<br>

app/views/orders/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel-default panel">
      <div class="panel-heading">
        <h4>Confirm your order</h4>
      </div>
      <div class="panel-body">

        <p id="notice"><%= notice %></p>

        <p>
          <strong>Supply title: </strong>
          <%= @supply.title %>
        </p>

        <p>
          <strong>Price:</strong>
          <%= @supply.price %> UAH
        </p>

        <p>
          <strong>User:</strong>
          <%= @user.email %>
        </p>

        <p>
          <strong>Delivery Date:</strong>
          <%= Date.today + 1 %>
        </p>

        <p>
          <strong>Status:</strong>
          Pending
        </p>


        <%= form_for(@order, :url=>{:action=>'create'}) do |f| %>
            <%= f.hidden_field :supply_id, :value => @supply.id %>
            <%= f.hidden_field :status, :value => "Pending" %>
            <%= f.hidden_field :deliveryDate, :value => Date.today + 3 %>

            <div class="form-group">
              <%= f.label :count, class: 'control-label' %> <br/>
              <%= f.number_field :count, class: 'form-control', type: 'number' %>
            </div>

            <div class="form-group">
              <%= f.submit 'Create', :class => 'btn btn-primary' %>
              <%= link_to 'Back', supplies_path, class: 'btn btn-default' %>
            </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel-default panel">
      <div class="panel-heading">
        <h4>Order # <%= @order.id %></h4>
      </div>
      <div class="panel-body">

        <p id="notice"><%= notice %></p>

        <p>
          <strong>User:</strong>
          <%= @order.user_id %>
        </p>

        <p>
          <strong>Supply:</strong>
          <%= @order.supply_id %>
        </p>

        <p>
          <strong>Count:</strong>
          <%= @order.count %>
        </p>

        <p>
          <strong>Total price:</strong>
          <%= @order.total %>
        </p>

        <p>
          <strong>Delivery Date:</strong>
          <%= @order.deliveryDate %>
        </p>

        <p>
          <strong>Query status:</strong>
          <%= @order.status %>
        </p>

        <%= link_to 'Back to shopping!', supplies_path, class: 'btn btn-info' %>
        <%= link_to 'Back', orders_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>