config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  get 'orders/info' => 'orders#info'
  get 'supplies/info' => 'supplies#info'

  resources :supplies

  resources :orders

  resources :users
  
  root to: "supplies#index"

end

app/models/supply.rb
class Supply < ActiveRecord::Base
end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  
  before_filter :authenticate_user!
  before_action :set_supply, only: [:show, :edit, :update, :destroy]

  # GET /supplies
  # GET /supplies.json
  def index
    @supplies = Supply.all
  end

  # GET /supplies/1
  # GET /supplies/1.json
  def show
  end

  # GET /supplies/new
  def new
    @supply = Supply.new
  end

  # GET /supplies/1/edit
  def edit
  end

  # POST /supplies
  # POST /supplies.json
  def create
    @supply = Supply.new(supply_params)

    respond_to do |format|
      if @supply.save
        format.html { redirect_to @supply, notice: 'Supply was successfully created.' }
        format.json { render :show, status: :created, location: @supply }
      else
        format.html { render :new }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supplies/1
  # PATCH/PUT /supplies/1.json
  def update
    respond_to do |format|
      if @supply.update(supply_params)
        format.html { redirect_to @supply, notice: 'Supply was successfully updated.' }
        format.json { render :show, status: :ok, location: @supply }
      else
        format.html { render :edit }
        format.json { render json: @supply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supplies/1
  # DELETE /supplies/1.json
  def destroy
    @supply.destroy
    respond_to do |format|
      format.html { redirect_to supplies_url, notice: 'Supply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supply
      @supply = Supply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supply_params
      params.require(:supply).permit(:title, :description, :price)
    end
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/views/supplies/_form.html.erb
<%= form_for(@supply) do |f| %>
  <% if @supply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@supply.errors.count, "error") %> prohibited this supply from being saved:</h2>

      <ul>
      <% @supply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label' %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label'  %><br>
    <%= f.text_area :description, class: 'form-control'  %>
  </div>
  <div class="form-group">
    <%= f.label :price, class: 'control-label'  %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', :class => 'btn btn-primary' %>
    <%= link_to 'Back', supplies_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/supplies/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>Edit supply</h4>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/supplies/index.html.erb
<div class="container">

  <h1>Supplies</h1>

  <table class="table table-bordered">
    <thead>
    <tr>
      <th class="text-center">ID</th>
      <th class="text-center">Title</th>
      <th class="text-center">Description</th>
      <th class="text-center">Price</th>
      <th class="text-center">Actions</th>
    </tr>
    </thead>

    <tbody>
    <% @supplies.each do |supply| %>
        <tr>
          <td><%= supply.id %></td>
          <td><%= supply.title %></td>
          <td><%= supply.description %></td>
          <td><%= supply.price %> UAH</td>
          <td class="text-center">
            <% if current_user.admin? %>
                <%= link_to 'Show', supply, class: 'btn btn-default' %>
                <%= link_to 'Edit', edit_supply_path(supply), class: 'btn btn-info' %>
                <%= link_to 'Destroy', supply, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
            <% end %>
            <%= link_to 'Buy', new_order_path(:supply_id => supply.id), class: 'btn btn-primary'  %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
  <br/>
  <% if current_user.admin? %>
      <%= link_to 'New Supply', new_supply_path, class: 'btn btn-primary' %>
  <% end %>
  <%= link_to 'Show orders', orders_path, class: 'btn btn-default' %>
</div>

app/views/supplies/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>New supply</h4>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/supplies/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel-default panel">
      <div class="panel-heading">
        <h4>Supply # <%= @supply.id %></h4>
      </div>
      <div class="panel-body">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Title:</strong>
          <%= @supply.title %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @supply.description %>
        </p>

        <p>
          <strong>Price:</strong>
          <%= @supply.price %> UAH
        </p>

        <%= link_to 'Edit', edit_supply_path(@supply), class: 'btn btn-info' %>
        <%= link_to 'Back', supplies_path, class: 'btn btn-default' %>
      </div>
    </div>
  </div>
</div>