config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }

  get 'orders/info' => 'orders#info'
  get 'supplies/info' => 'supplies#info'

  resources :supplies

  resources :orders

  resources :users
  
  root to: "supplies#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">E-Commerce</a>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Supplies', supplies_path %></li>
          <li><%= link_to 'Orders', orders_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to 'Users', users_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="user-hello">
            Hello, <%= current_user.email %>
            <% if current_user.admin? %>
                ( Administrator )
            <% end %>
          </li>
          <li><%= link_to 'Logout', destroy_user_session_path, :method => :delete %></li>
        </ul>
      </div>
    </div>
  </nav>

    <form action="">
      <fieldset></fieldset>
      <fieldset></fieldset>
      <fieldset></fieldset>
    </form>


<% end %>
<section class="content">
  <%= yield %>
</section>


</body>
</html>